name: build module

on:
  workflow_dispatch:
    inputs:
      module-name:
        required: true
        type: string
      build-number:
        required: true
        type: string

jobs:
  build-module:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.2
          cache: pip
          cache-dependency-path: |
            src/aviationapi/requirements.txt

      - name: install dependencies
        run: pip install -r src/aviationapi/requirements.txt

      - name: build
        run: ./src/aviationapi/scripts/build.sh ${{ github.event.inputs.module-name }}
        env:
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ vars.BUILD_S3_BUCKET_NAME }}
          BUILD_NUMBER: ${{ github.event.inputs.build-number }}

