name: build module

on:
  workflow_call:
    inputs:
      module-name:
        required: true
        type: string
      build-number:
        required: true
        type: string
    outputs:
      build-name:
        value: ${{ jobs.build-module.outputs.build-name }}
    secrets:
      BUILD_AWS_ACCESS_KEY_ID:
        required: true
      BUILD_AWS_SECRET_ACCESS_KEY:
        required: true


jobs:
  build-module:
    runs-on: ubuntu-latest
    outputs:
      build-name: ${{ steps.build.outputs.build-name }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.2
          cache: pip
          cache-dependency-path: |
            src/aviationapi/requirements.txt

      - name: build
        id: build
        run: ./src/aviationapi/scripts/build.sh ${{ inputs.module-name }}
        env:
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ vars.BUILD_S3_BUCKET_NAME }}
          BUILD_NUMBER: ${{ inputs.build-number }}

