name: deploy
on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment
      build-name:
        required: true
        type: string

permissions:
  id-token: write

jobs:
  get-lambda-name:
    runs-on: ubuntu-latest
    outputs:
      lambda-name: ${{ steps.get-lambda-name.outputs.lambda-name }}

    steps:
      - name: get lambda name from build name
        id: get-lambda-name
        run: |
          FULL_NAME="aviationapi-${{ inputs.build-name }}"
          echo "lambda-name=${FULL_NAME%-*-*-*}" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: get-lambda-name

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: deploy
        run: ./src/aviationapi/scripts/deploy.sh
        env:
          LAMBDA_FUNCTION_NAME: ${{ needs.get-lambda-name.outputs.lambda-name }}
          S3_BUCKET_NAME: ${{ vars.BUILD_S3_BUCKET_NAME }}
          BUILD_NAME: ${{ inputs.build-name }}
          AWS_PAGER: ""
