name: validate code

on:
  workflow_dispatch:

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.2
          cache: pip
          cache-dependency-path: |
            src/aviationapi/requirements.txt
            src/aviationapi/requirements.ci.txt

      - name: install dependencies
        run: pip install -r src/aviationapi/requirements.txt -r src/aviationapi/requirements.ci.txt

      - name: check formatting
        run: ./src/aviationapi/scripts/format.sh -c


  test:
    runs-on: ubuntu-latest
    needs: check-format

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.2
          cache: pip
          cache-dependency-path: |
            src/aviationapi/requirements.txt
            src/aviationapi/requirements.ci.txt

      - name: install dependencies
        run: pip install -r src/aviationapi/requirements.txt -r src/aviationapi/requirements.ci.txt

      - name: run tests
        run: pytest --junit-xml=test-results.xml

      - name: generate test report
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          fail-on-empty: true
