name: validate terraform

on:
  workflow_call:
    secrets:
      TF_ROLE_ARN:
        required: true
      TF_BACKEND_ROLE_ARN:
        required: true

permissions:
  id-token: write

jobs:
  plan-sandbox:
    runs-on: ubuntu-latest
    environment: sandbox
    env:
      TF_VAR_ENV: ${{ vars.TF_VAR_ENV }}
      TF_VAR_ENV_SUFFIX: ${{ vars.TF_VAR_ENV_SUFFIX }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup aws credentials
        uses: ./.github/actions/setup-tf-aws-credentials-action
        with:
          TF_ROLE_ARN: ${{ secrets.TF_ROLE_ARN }}
          TF_BACKEND_ROLE_ARN: ${{ secrets.TF_BACKEND_ROLE_ARN }}
          AWS_REGION: ${{ vars.AWS_REGION }}

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      - name: terraform init
        run: |
          cd terraform
          terraform init

      - name: terraform check format
        run: |
          cd terraform
          terraform fmt -check

      - name: terraform plan
        run: |
          cd terraform
          terraform workspace select sandbox
          terraform plan

  plan-staging:
    runs-on: ubuntu-latest
    environment: staging
    env:
      TF_VAR_ENV: ${{ vars.TF_VAR_ENV }}
      TF_VAR_ENV_SUFFIX: ${{ vars.TF_VAR_ENV_SUFFIX }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup aws credentials
        uses: ./.github/actions/setup-tf-aws-credentials-action
        with:
          TF_ROLE_ARN: ${{ secrets.TF_ROLE_ARN }}
          TF_BACKEND_ROLE_ARN: ${{ secrets.TF_BACKEND_ROLE_ARN }}
          AWS_REGION: ${{ vars.AWS_REGION }}

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      - name: terraform init
        run: |
          cd terraform
          terraform init

      - name: terraform plan
        run: |
          cd terraform
          terraform workspace select staging
          terraform plan

  plan-prod:
    runs-on: ubuntu-latest
    environment: prod
    env:
      TF_VAR_ENV: ${{ vars.TF_VAR_ENV }}
      TF_VAR_ENV_SUFFIX: ${{ vars.TF_VAR_ENV_SUFFIX }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup aws credentials
        uses: ./.github/actions/setup-tf-aws-credentials-action
        with:
          TF_ROLE_ARN: ${{ secrets.TF_ROLE_ARN }}
          TF_BACKEND_ROLE_ARN: ${{ secrets.TF_BACKEND_ROLE_ARN }}
          AWS_REGION: ${{ vars.AWS_REGION }}

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      - name: terraform init
        run: |
          cd terraform
          terraform init

      - name: terraform plan
        run: |
          cd terraform
          terraform workspace select prod
          terraform plan

