name: validate terraform

on:
  workflow_call:
    secrets:
      TF_ROLE_ARN:
        required: true
      TF_BACKEND_ROLE_ARN:
        required: true

permissions:
  id-token: write

jobs:
  sandbox:
    uses: iccowan/AviationAPIv2/.github/workflows/tf-plan.yml@main
    with:
      environment: sandbox
    secrets:
      TF_ROLE_ARN: ${{ secrets.TF_ROLE_ARN }}
      TF_BACKEND_ROLE_ARN: ${{ secrets.TF_BACKEND_ROLE_ARN }}

  staging:
    uses: iccowan/AviationAPIv2/.github/workflows/tf-plan.yml@main
    with:
      environment: staging
    secrets:
      TF_ROLE_ARN: ${{ secrets.TF_ROLE_ARN }}
      TF_BACKEND_ROLE_ARN: ${{ secrets.TF_BACKEND_ROLE_ARN }}

  prod:
    uses: iccowan/AviationAPIv2/.github/workflows/tf-plan.yml@main
    with:
      environment: prod
    secrets:
      TF_ROLE_ARN: ${{ secrets.TF_ROLE_ARN }}
      TF_BACKEND_ROLE_ARN: ${{ secrets.TF_BACKEND_ROLE_ARN }}
